function D = D_matrix(in1,V,U)
%D_matrix
%    D = D_matrix(IN1,V,U)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    04-Jan-2024 09:13:50

theta = in1(:,3);
t2 = cos(theta);
t3 = t2.^2;
D = [0.0;0.0;(-5.4e+1./5.0)./(t3.*(4.05e+2./2.0)-1.485e+3);(t2.*1.8e+1)./(t3.*2.025e+3-1.485e+4)];
end
