function D = D_matrix(in1,V,U)
%D_matrix
%    D = D_matrix(IN1,V,U)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Jan-2024 16:22:29

theta = in1(:,3);
t2 = cos(theta);
t3 = t2.^2;
D = [0.0;0.0;(-6.21e+2./5.0e+2)./(t3.*(4.05e+2./2.0)-1.485e+3);(t2.*(2.07e+2./1.0e+2))./(t3.*2.025e+3-1.485e+4)];
end
