function M = H_matrix(in1,in2)
%H_matrix
%    M = H_matrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Dec-2023 12:06:19

M = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
end
