function H = H_matrix(in1)
%H_matrix
%    H = H_matrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Dec-2023 12:12:42

theta = in1(:,3);
xc = in1(:,1);
t2 = cos(theta);
t3 = imag(xc);
t4 = sin(theta);
t5 = real(xc);
t6 = imag(t2);
t7 = real(t2);
t8 = imag(t4);
t9 = real(t4);
t10 = t6.*3.0;
t11 = t7.*3.0;
t12 = t8.*3.0;
t13 = t9.*3.0;
t14 = -t11;
t15 = t5+t10+t13;
t16 = t3+t12+t14;
t17 = t15.^2;
t18 = t16.^2;
t19 = t17+t18;
t20 = 1.0./t19;
H = reshape([-1.0,-t16.*t20,0.0,0.0,0.0,1.0e+1,0.0,t17.*t20.*((t10+t13)./t15-(t16.*(t11-t12))./t17),0.0,0.0,0.0,0.0],[3,4]);
end
